### ISSUE TITLE
Connecting iMSTK to third party tools like Message Queues

### ISSUE THREAD

**Issue by Berthelmaster** [Kitware/iMSTK#1]
Hi

I'm doing a bit of research on potential frameworks for Digital Twin Simulations.

Are there any official guidelines for connecting simulations with TCP-based systems like Message buses or other forms of APIs?

Thank!

BR
Thomas

**Comment by HarryDC** [comment]
Can you clarify that a little bit more ? Are you looking to control the simulation via TCP, communicate about results and visualize remotely or other functionalities ? 

Right now iMSTK support the VRPN device driver that can communicate via TCP, this means you currently can add a input device and control the simulation via TCP/IP but this is only for devices. The simulation and visualization parts at the moment will only be running locally

**Comment by Berthelmaster** [comment]
Hi Harry

Sorry about the imprecise description.

Yes kinda, we have simulation hardware that tracks a number of things on haptic devices. We're working on a digital twin simulation, where we think your framework could visualize and make correction based on the input from the simulation hardware. At the moment our design is to relay this to your framework or another (we haven't decided yet) using TCP/IP. We are aware that there will be some propagation delay due to the nature of networking, but that should be okay in our scenario. For a number of reasons, it's not possible for us directly to connect the haptic device used by the user to the iMSTK, however if an event driven TCP/IP connection could be established, I think that could work well. However I'm not able to find the documentation for this. E.g in iMSTK case the SimulationManager would wait for events and trigger updates on the components based on this? Please correct me if I'm misunderstanding your framework.

Thanks a lot!

**Comment by HarryDC** [comment]
An unmodified simulation manager would run all the time as iMSTK is geared towards real time simulation. But as long as you are ok with ONE simulation manager and visualizing on ONE screen, you should look into the VRPN device driver (https://gitlab.kitware.com/iMSTK/iMSTK/-/blob/master/Source/Devices/imstkVRPNDeviceClient.h and https://gitlab.kitware.com/iMSTK/iMSTK/-/blob/master/Source/Devices/imstkVRPNDeviceManager.h) (https://github.com/vrpn/vrpn) it does connect to iMSTK via TCP/IP, on the iMSTK side you would use a RigidController same is in the local case to control a rigid in the simulation scene.

Caveat is that we currently have not implemented/tested the haptic output via VRPN, we are also not at the Head of the VRPN branch. So the setup that is achievable with a small amount of effort would be 
```

          ┌─────────────────────┐
          │Imstk Sim Machine    │
          │Simulation Manager   │
          │Visualization        │
          └──────────▲──────────┘
                     │
                     │
                     │   TCP/IP
                     │
          ┌──────────▼─────────┐
          │ VRPN Server Machine│
          └──────────▲─────────┘
                     │
                     │    Local Connection
          ┌──────────▼─────────┐
          │   Haptic Device    │
          └────────────────────┘

```
That would require extending the DeviceManager class to manage the force feedback callback and back channel

**Comment by HarryDC** [comment]
@Berthelmaster you can also message me at harald.scheirich@kitware.com if you need a more detailed discussion

**Comment by Berthelmaster** [comment]
Alright, that was what I was looking for, we'll take a look. We appreciate your support! I'll close this issue.

BR
Thomas
